language: groovy
sudo: false
jdk:
- oraclejdk8

branches:
  only:
  - master

before_install:
- chmod +x gradlew

install:
- ./gradlew assemble

script:
- ./gradlew check

after_sucess:
- echo "`find ./ -name "*.war"`"
