language: groovy
sudo: false
jdk:
- oraclejdk7

branches:
  only:
  - master

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g' | tr -d "\r"`
- echo "GRAILS_VERSION:$GRAILS_VERSION"
- gvm install grails $GRAILS_VERSION || true

script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war --non-interactive && grails prod maven-install --non-interactive
